import { z } from "zod";

const envSchema = z.object({
  DATABASE_URL: z.string().min(1),
  DIRECT_DATABASE_URL: z.string().optional(),
  DB_MIGRATION_FALLBACK_PUSH: z.string().optional(),
  DB_STARTUP_MAX_RETRIES: z.string().optional(),
  DB_STARTUP_RETRY_DELAY_MS: z.string().optional(),
  AUTH_SECRET: z.string().min(1),
  AUTH_URL: z.string().url().optional(),
  AUTH_GOOGLE_ID: z.string().optional(),
  AUTH_GOOGLE_SECRET: z.string().optional(),
  RESEND_API_KEY: z.string().optional(),
  EMAIL_FROM: z.string().default("WayWork <noreply@waywork.com>"),
  STRIPE_SECRET_KEY: z.string().optional(),
  STRIPE_PUBLISHABLE_KEY: z.string().optional(),
  STRIPE_WEBHOOK_SECRET: z.string().optional(),
  STRIPE_CONNECT_WEBHOOK_SECRET: z.string().optional(),
  R2_ACCOUNT_ID: z.string().optional(),
  R2_ACCESS_KEY_ID: z.string().optional(),
  R2_SECRET_ACCESS_KEY: z.string().optional(),
  R2_BUCKET_NAME: z.string().default("waywork"),
  R2_PUBLIC_URL: z.string().optional(),
  NEXT_PUBLIC_MAPBOX_TOKEN: z.string().optional(),
  MEWS_API_BASE_URL: z.string().url().optional(),
  MEWS_CLIENT_TOKEN: z.string().optional(),
  MEWS_CONNECTION_TOKEN: z.string().optional(),
  MEWS_ACCESS_TOKEN: z.string().optional(),
  MEWS_ENTERPRISE_ID: z.string().optional(),
  MEWS_WEBHOOK_SECRET: z.string().optional(),
  PMS_SYNC_CRON_SECRET: z.string().optional(),
  SENTRY_DSN: z.string().optional(),
  SENTRY_TRACES_SAMPLE_RATE: z.string().optional(),
  NEXT_PUBLIC_APP_URL: z.string().url().default("http://localhost:3000"),
});

export const env = envSchema.parse(process.env);
